
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_CM36652_NEW),y)
obj-y	+=  cm36652-new/
endif

#@wming add{
ifeq ($(CONFIG_MTK_TMD2772),y)
obj-y	+=  tmd2772/
endif
#@}

