
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_YAS532),y)
obj-y	+=  yamaha532/
endif

#@ add by wming{
ifeq ($(CONFIG_MTK_MC64XX),y)
obj-y   +=  mc64xx/
endif
#@}
