
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_MPU6515A),y)
obj-y	+=  mpu6515/
endif

#@wming{
ifeq ($(CONFIG_MTK_MC3XXX),y)
obj-y   +=  mc3xxx/
endif
#@}
